# brace_style = "AlwaysNextLine"
# control_brace_style = "AlwaysNextLine"

# enum_discrim_align_threshold = 20
# struct_field_align_threshold = 20
fn_params_layout = "Vertical"

# format_code_in_doc_comments = true
# format_generated_files = true
# format_macro_matchers = true
# format_macro_bodies = true

hard_tabs = true

# imports_indent = "Visual"
# imports_layout = "Vertical"
# indent_style = "Visual"

match_block_trailing_comma = true

# imports_granularity = "Module"

# reorder_impl_items = true
reorder_imports = true
reorder_modules = true

# space_before_colon = true
# spaces_around_ranges = true

# trailing_comma = "Always"
# trailing_semicolon = true

# wrap_comments = true

# force_multiline_blocks = true